meta_title: "Get The Sound"
meta_description: "In Chill We Trust"
meta_image: "meta_image.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@_getthesound" # indispensable pour les Twitter Cards
